### ISSUE TITLE
Use hased passwords

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-etherpad#14]
There is a plugin https://www.npmjs.com/package/ep_hash_auth, "Allow the use of hashed passwords in etherpad-lite". This plugin allows the usage of hash values for authentoication in settings.json.

Consider installing this by default and hash the passwords.

**Comment by drybjed** [comment]
Good idea, can Ansible generate those hashes via `lookup("password")`?

**Comment by ypid** [comment]
The current state of `ep_hash_auth` does not provide much extra security. It uses one round of SHA512 for hashing. No option to change the number of rounds. I "forked" (source not yet on github) the thing and changed it to bcrypt and waiting for response from the maintainer currently. It might be required to convert the password with a command in Ansible to the hash for now.

**Comment by drybjed** [comment]
@ypid Great. BTW, be advised that I've switched Travis tests to Ansible v2. Currently there are some issues, I'm working them out.

**Comment by ypid** [comment]
Thanks for the heads up.

**Comment by LaKing** [comment]
With ep_hash_auth 2.x there is an update on this.

Greetings, ...

**Comment by drybjed** [comment]
The `debops.etherpad` v0.2.0 version now uses SHA512 hashed passwords by default.
