### ISSUE TITLE
Switch `/srv/users` to `{{ ansible_local.root.app }}`?

### ISSUE THREAD

**Issue by ypid** [debops/ansible-etherpad#15]
I almost done with my rework of this role and tried to deploy against a fresh system. With `debops.mariadb` it wants to create `/srv/users/etherpad-lite` but fails because `/srv/users` has never been created. I suggest switching to `{{ ansible_local.root.app }}` although it will break backwards compatibility. What do you think?

**Comment by drybjed** [comment]
Sure, definitely. Just make sure that you provide a default (as usuall with Ansible local facts, you need to check every leaf of a dict) and it should be fine.
