### ISSUE TITLE
Use sqlite as default DB?

### ISSUE THREAD

**Issue by htgoebel** [debops/ansible-etherpad#5]
I wonder if using sqlite as default DB would be a good idea. It would save setting up a database engine like mysql and still be better than dirty. And should be okay for smaller installations.

**Comment by drybjed** [comment]
Actually, how about `redis`? It's memory based with sporadic saves to disk, could help with performance.

**Comment by drybjed** [comment]
And wouldn't `sqlite` database locking pose a problem with multiple users? Or does `etherpad` handle that without issues?

**Comment by htgoebel** [comment]
Re: redis: IMHO this is not a good idea, because the [user_pad](https://github.com/aoberegg/ep_user_pad/) requires a sql-database.
Re sqlite: Never heard of this. sqlite is a full featured database-engine, so I would wonder if this is a problem.

**Comment by drybjed** [comment]
In that case, sure - let's go with `sqlite` as default. It's easy enough to change if needed.
