### ISSUE TITLE
Task fails when etherpad_home is not default

### ISSUE THREAD

**Issue by Mboyer** [debops/ansible-etherpad#9]
etherpad_home: '/srv/etherpad'

TASK: [debops.etherpad | Clone Etherpad source code] *************************\* 
failed: [admin5] => {"cmd": "/usr/bin/git clone --bare https://github.com/ether/etherpad-lite /srv/etherpad/src/gitlab.com/ether/etherpad-lite", "failed": true, "rc": 128}
stderr: fatal: could not create leading directories of '/srv/etherpad/src/gitlab.com/ether/etherpad-lite'

msg: fatal: could not create leading directories of '/srv/etherpad/src/gitlab.com/ether/etherpad-lite'

**Comment by drybjed** [comment]
This task is run via `sudo` on Etherpad user. Since `/srv` is owned by root, that user cannot create new directories there. However that's weird since home directory should be created... Is `/srv/etherpad` present?

**Comment by Tremoflux** [comment]
No, it created /srv/user/etherpad-lite instead.

**Comment by drybjed** [comment]
The default home directory in the `debops.etherpad` role is now `/var/local/etherpad-lite/` which should be created by the role. I'm closing this issue as resolved.
